### ISSUE TITLE
Nhóm mình đã hoàn thành sơ bộ và nhờ các bạn góp ý

### ISSUE THREAD

**Issue by quocPhat1902** [HMy2912/P4DS-FinalProj#1]
Đến hôm nay thì nhóm mình đã hoàn thành đc 75% đồ án, các câu hỏi đã được giải quyết và tìm ra câu trả lời. Các bạn vào xem và góp ý những lỗi sai giúp mình nhé. Cảm ơn các bạn

**Comment by HMy2912** [comment]
Cơ bản nhóm có 4 câu hỏi, đều có trực quan hóa và trả lời nhưng chưa được sâu sắc. Mong các bạn nhóm khác sẽ có nhận xét về phần này của nhóm mình.
Các phần giới thiệu, tiền xử lý, xem xét phân bố các thuộc tính, trả lời câu hỏi đã hoàn tất. Phần tự đánh giá sẽ bổ sung sau.

**Comment by zaivi** [comment]
Xin chào nhóm 14, mình là thành viên của nhóm 13,

Mình có vài góp ý sau:
- Sau khi đọc và suy nghĩ tập dữ liệu của bạn chọn, thì hình như dữ liệu nói về `khảo sát tình trạng bệnh ảnh hưởng đến việc làm`, mình thấy khá hay.
- Nhưng có vấn đề là các trường dữ liệu thu thập được khá dài, trong file jupyter mình không thể xem hết tất cả `63 trường dữ liệu`, mình hiểu là survey nên dữ liệu sẽ như thế. Nhưng mình đọc không hết thì cũng không biết nhận xét như nào ...
- Để thêm tính tổng quan và dễ hiểu, nhóm nên thêm `Mục Lục` ở phần đầu
- Phần `Sự phân bố của các biến categorical và numeric`, nhóm chưa có nhận xét nên mình skip nhé
- Phần `Trả lời cho 4 câu hỏi`, mình nhận thấy khá nhiều biểu đồ, theo mình thì khá rối mắt (do biểu đồ nhiều + code dài trên một cell), mình nghĩ nên tách ra những biểu đồ nào liên quan thành 1 cell rồi bên dưới là phần nhận xét cho một nhóm biểu đồ  đó. `Ở câu hỏi thứ 2`, nhóm để 8 biểu đồ một lúc và nhận xét chung thì đọc cũng không hiểu rõ đang nói đến biểu đồ nào (mình đang làm storytelling, nên giải thích với biểu đồ đó)
- Phần `code`, thì mình thấy nhóm plot biểu đồ nhiều, nên sự trùng lặp code khá nhiều làm cho cell dài ra (Mình lướt cũng khá mỏi tay + làm cho mình hơi chán), mình nghĩ nên gom lại thành `function kèm với parameter` thì việc tái sử dụng cho các biểu đồ gần như chỉ cần gọi `1 dòng code `
- Về `Nội dung nhận xét cho các biểu đồ`, mình thấy nhóm làm cũng ngắn và chưa rõ ý, theo mình nên dẫn dắt người đọc bằng các vấn đề của xã hội (như thêm bài báo chẳng hạn hoặc những nghiên cứu, ...)
---
Cám ơn các bạn,
Giai Vĩ

**Comment by HMy2912** [comment]
> Xin chào nhóm 14, mình là thành viên của nhóm 13,
> 
> Mình có vài góp ý sau:
> 
> * Sau khi đọc và suy nghĩ tập dữ liệu của bạn chọn, thì hình như dữ liệu nói về `khảo sát tình trạng bệnh ảnh hưởng đến việc làm`, mình thấy khá hay.
> * Nhưng có vấn đề là các trường dữ liệu thu thập được khá dài, trong file jupyter mình không thể xem hết tất cả `63 trường dữ liệu`, mình hiểu là survey nên dữ liệu sẽ như thế. Nhưng mình đọc không hết thì cũng không biết nhận xét như nào ...
> * Để thêm tính tổng quan và dễ hiểu, nhóm nên thêm `Mục Lục` ở phần đầu
> * Phần `Sự phân bố của các biến categorical và numeric`, nhóm chưa có nhận xét nên mình skip nhé
> * Phần `Trả lời cho 4 câu hỏi`, mình nhận thấy khá nhiều biểu đồ, theo mình thì khá rối mắt (do biểu đồ nhiều + code dài trên một cell), mình nghĩ nên tách ra những biểu đồ nào liên quan thành 1 cell rồi bên dưới là phần nhận xét cho một nhóm biểu đồ  đó. `Ở câu hỏi thứ 2`, nhóm để 8 biểu đồ một lúc và nhận xét chung thì đọc cũng không hiểu rõ đang nói đến biểu đồ nào (mình đang làm storytelling, nên giải thích với biểu đồ đó)
> * Phần `code`, thì mình thấy nhóm plot biểu đồ nhiều, nên sự trùng lặp code khá nhiều làm cho cell dài ra (Mình lướt cũng khá mỏi tay + làm cho mình hơi chán), mình nghĩ nên gom lại thành `function kèm với parameter` thì việc tái sử dụng cho các biểu đồ gần như chỉ cần gọi `1 dòng code `
> * Về `Nội dung nhận xét cho các biểu đồ`, mình thấy nhóm làm cũng ngắn và chưa rõ ý, theo mình nên dẫn dắt người đọc bằng các vấn đề của xã hội (như thêm bài báo chẳng hạn hoặc những nghiên cứu, ...)
> 
> Cám ơn các bạn, Giai Vĩ

**Comment by HMy2912** [comment]
Cám ơn bạn Vĩ nhé, nhóm mình xin ghi nhận góp ý của bạn. Cám ơn bạn, chúc bạn hoàn thành môn học thật tốt.

**Comment by PNTAN19** [comment]
Xin chào nhóm 14, mình là Ân của nhóm 13, ngoài nhận xét của bạn Giai thì mình có nhận xét sau:

- Các cột dữ liệu ấy, bạn nên xuất 10 cột 1 lần là sẽ bao quát được tất cả các trường dữ liệu. Phần giải thích cũng bị ... nên rất khó theo dõi.
- Nhóm bạn bị thiếu phần nêu ra một cột có bao nhiêu giá trị, và liệt kê một vài giá trị khác nhau của cột đó.
- Những cái cột flag, mình nghĩ nó là categorical, tại vì nó chỉ có 2 giá trị.
- Chỗ bạn xóa các cột >= 50% missing values, bạn ghi nhầm cols thành rows.
- Câu 1, hình như bạn bị ngược men and women, mình thấy men chọn nhiều hơn women mà, phải không?
- Sau mỗi hình bạn nên thêm dấu chấm phẩy ở đoạn code cuối, để khi chạy nó chỉ xuất ra màn hình cái hình thôi.

Tổng thể:
- Các bạn chọn câu hỏi rất hay, ý nghĩa và dùng đồ thị hợp lý để miêu tả cho câu hỏi của mình.
- Ngữ pháp tiếng anh cũng tốt, viết rất chặt.
- Dataset của các bạn mình thấy khó thật mà các bạn làm như vậy là quá tốt. Chúc các bạn sớm hoàn thành.

Thân,
Ân.
